blank_issues_enabled: true
contact_links:
  - name: Sicherheitslücke melden
    url: https://github.com/ullrichc/WLANalarm/security/advisories/new
    about: Bitte nicht öffentlich melden, sondern über Security Advisories.
